version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}-{{ checksum "project/plugins.sbt" }}-{{ checksum ".circleci/config.yml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Check formatting with Scalafmt
          command: cat /dev/null | sbt scalafmt::test test:scalafmt::test it:scalafmt::test

      - run:
          name: Compile
          command: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.m2
            - ~/.ivy2/cache
            - target/resolution-cache
            - target/streams
            - project/target/resolution-cache
            - project/target/streams
          key: v1-dependencies-{{ checksum "build.sbt" }}-{{ checksum "project/plugins.sbt" }}-{{ checksum ".circleci/config.yml" }}

      - run:
          name: Run unit and integration tests
          command: cat /dev/null | sbt test it:test

  publish:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run: ssh-add -D && echo "${GITHUB_SSH_KEY}" | base64 --decode | ssh-add -

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}-{{ checksum "project/plugins.sbt" }}-{{ checksum ".circleci/config.yml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Publish Artifact
          command: .circleci/release.sh

      - run:
          name: Update GH site
          command: sbt make-site ghpagesPushSite

workflows:
  version: 2
  test_and_publish:
    jobs:
      - test:
          context: PagerDuty
          filters:
            branches:
              ignore: /gh-pages.*/
      - publish:
          requires:
            - test
          context: PagerDuty
          filters:
            branches:
              only: master

